package com.cppteam.pojo;

import java.io.Serializable;

public class Day implements Serializable {
    private static final long serialVersionUID = 2965716893500189807L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day.id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day.journey_id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String journeyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day.count
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day.id
     *
     * @return the value of day.id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day.id
     *
     * @param id the value for day.id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day.journey_id
     *
     * @return the value of day.journey_id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getJourneyId() {
        return journeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day.journey_id
     *
     * @param journeyId the value for day.journey_id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setJourneyId(String journeyId) {
        this.journeyId = journeyId == null ? null : journeyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day.count
     *
     * @return the value of day.count
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day.count
     *
     * @param count the value for day.count
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}