package com.cppteam.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * @author happykuan
 */
public class Follower implements Serializable{
    private static final long serialVersionUID = 8597316191740707574L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follower.id
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follower.user_id
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follower.join_time
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    private Date joinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follower.sponsor_id
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    private String sponsorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follower.id
     *
     * @return the value of follower.id
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follower.id
     *
     * @param id the value for follower.id
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follower.user_id
     *
     * @return the value of follower.user_id
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follower.user_id
     *
     * @param userId the value for follower.user_id
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follower.join_time
     *
     * @return the value of follower.join_time
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follower.join_time
     *
     * @param joinTime the value for follower.join_time
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follower.sponsor_id
     *
     * @return the value of follower.sponsor_id
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    public String getSponsorId() {
        return sponsorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follower.sponsor_id
     *
     * @param sponsorId the value for follower.sponsor_id
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    public void setSponsorId(String sponsorId) {
        this.sponsorId = sponsorId == null ? null : sponsorId.trim();
    }
}