package com.cppteam.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;
import java.util.Date;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class Journey implements Serializable{
    private static final long serialVersionUID = 120250778956679805L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.id
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.name
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.day_num
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    private Integer dayNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.type
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.img
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.status
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.img_thumb
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    private String imgThumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.creator_id
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.create_time
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.college_cId
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    private Integer collegeCid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.id
     *
     * @return the value of journey.id
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.id
     *
     * @param id the value for journey.id
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.name
     *
     * @return the value of journey.name
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.name
     *
     * @param name the value for journey.name
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.day_num
     *
     * @return the value of journey.day_num
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public Integer getDayNum() {
        return dayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.day_num
     *
     * @param dayNum the value for journey.day_num
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public void setDayNum(Integer dayNum) {
        this.dayNum = dayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.type
     *
     * @return the value of journey.type
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.type
     *
     * @param type the value for journey.type
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.img
     *
     * @return the value of journey.img
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.img
     *
     * @param img the value for journey.img
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.status
     *
     * @return the value of journey.status
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.status
     *
     * @param status the value for journey.status
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.img_thumb
     *
     * @return the value of journey.img_thumb
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public String getImgThumb() {
        return imgThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.img_thumb
     *
     * @param imgThumb the value for journey.img_thumb
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public void setImgThumb(String imgThumb) {
        this.imgThumb = imgThumb == null ? null : imgThumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.creator_id
     *
     * @return the value of journey.creator_id
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.creator_id
     *
     * @param creatorId the value for journey.creator_id
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.create_time
     *
     * @return the value of journey.create_time
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.create_time
     *
     * @param createTime the value for journey.create_time
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.college_cId
     *
     * @return the value of journey.college_cId
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public Integer getCollegeCid() {
        return collegeCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.college_cId
     *
     * @param collegeCid the value for journey.college_cId
     *
     * @mbggenerated Sun Oct 29 10:56:54 CST 2017
     */
    public void setCollegeCid(Integer collegeCid) {
        this.collegeCid = collegeCid;
    }
}