package com.cppteam.pojo;

import java.io.Serializable;

public class Site implements Serializable {
    private static final long serialVersionUID = -1455568401933315036L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.day_id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String dayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.name
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.time
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private Float time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.img
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.count
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.img_thumb
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String imgThumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.tips
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String tips;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.id
     *
     * @return the value of site.id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.id
     *
     * @param id the value for site.id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.day_id
     *
     * @return the value of site.day_id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getDayId() {
        return dayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.day_id
     *
     * @param dayId the value for site.day_id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setDayId(String dayId) {
        this.dayId = dayId == null ? null : dayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.name
     *
     * @return the value of site.name
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.name
     *
     * @param name the value for site.name
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.time
     *
     * @return the value of site.time
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public Float getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.time
     *
     * @param time the value for site.time
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setTime(Float time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.img
     *
     * @return the value of site.img
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.img
     *
     * @param img the value for site.img
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.count
     *
     * @return the value of site.count
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.count
     *
     * @param count the value for site.count
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.img_thumb
     *
     * @return the value of site.img_thumb
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getImgThumb() {
        return imgThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.img_thumb
     *
     * @param imgThumb the value for site.img_thumb
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setImgThumb(String imgThumb) {
        this.imgThumb = imgThumb == null ? null : imgThumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.tips
     *
     * @return the value of site.tips
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.tips
     *
     * @param tips the value for site.tips
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setTips(String tips) {
        this.tips = tips == null ? null : tips.trim();
    }
}