package com.cppteam.pojo;

import java.io.Serializable;

public class UserWx implements Serializable {
    private static final long serialVersionUID = -7273893392265584532L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wx.id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wx.access_token
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wx.expires_in
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private Integer expiresIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wx.refresh_token
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String refreshToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wx.openid
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wx.scope
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wx.unionid
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wx.user_id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wx.id
     *
     * @return the value of user_wx.id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wx.id
     *
     * @param id the value for user_wx.id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wx.access_token
     *
     * @return the value of user_wx.access_token
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wx.access_token
     *
     * @param accessToken the value for user_wx.access_token
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wx.expires_in
     *
     * @return the value of user_wx.expires_in
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public Integer getExpiresIn() {
        return expiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wx.expires_in
     *
     * @param expiresIn the value for user_wx.expires_in
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setExpiresIn(Integer expiresIn) {
        this.expiresIn = expiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wx.refresh_token
     *
     * @return the value of user_wx.refresh_token
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wx.refresh_token
     *
     * @param refreshToken the value for user_wx.refresh_token
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wx.openid
     *
     * @return the value of user_wx.openid
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wx.openid
     *
     * @param openid the value for user_wx.openid
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wx.scope
     *
     * @return the value of user_wx.scope
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wx.scope
     *
     * @param scope the value for user_wx.scope
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wx.unionid
     *
     * @return the value of user_wx.unionid
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wx.unionid
     *
     * @param unionid the value for user_wx.unionid
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wx.user_id
     *
     * @return the value of user_wx.user_id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wx.user_id
     *
     * @param userId the value for user_wx.user_id
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}