package com.cppteam.mapper;

import com.cppteam.pojo.College;
import com.cppteam.pojo.CollegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int countByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int deleteByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int insert(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int insertSelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    List<College> selectByExampleWithBLOBs(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    List<College> selectByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") College record, @Param("example") CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") College record, @Param("example") CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByExample(@Param("record") College record, @Param("example") CollegeExample example);
}