package com.cppteam.mapper;

import com.cppteam.pojo.Day;
import com.cppteam.pojo.DayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int countByExample(DayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int deleteByExample(DayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int insert(Day record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int insertSelective(Day record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    List<Day> selectByExample(DayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    Day selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") Day record, @Param("example") DayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByExample(@Param("record") Day record, @Param("example") DayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByPrimaryKeySelective(Day record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByPrimaryKey(Day record);
}