package com.cppteam.mapper;

import com.cppteam.pojo.Follower;
import com.cppteam.pojo.FollowerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FollowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follower
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    int countByExample(FollowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follower
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    int deleteByExample(FollowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follower
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follower
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    int insert(Follower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follower
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    int insertSelective(Follower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follower
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    List<Follower> selectByExample(FollowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follower
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    Follower selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follower
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") Follower record, @Param("example") FollowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follower
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    int updateByExample(@Param("record") Follower record, @Param("example") FollowerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follower
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    int updateByPrimaryKeySelective(Follower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follower
     *
     * @mbggenerated Wed Nov 01 22:06:25 CST 2017
     */
    int updateByPrimaryKey(Follower record);
}