package com.cppteam.mapper;

import com.cppteam.pojo.Site;
import com.cppteam.pojo.SiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int countByExample(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int deleteByExample(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int insert(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int insertSelective(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    List<Site> selectByExampleWithBLOBs(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    List<Site> selectByExample(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    Site selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") Site record, @Param("example") SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Site record, @Param("example") SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByExample(@Param("record") Site record, @Param("example") SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByPrimaryKeySelective(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByPrimaryKey(Site record);
}