package com.cppteam.mapper;

import com.cppteam.pojo.Sponsor;
import com.cppteam.pojo.SponsorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SponsorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int countByExample(SponsorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int deleteByExample(SponsorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int insert(Sponsor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int insertSelective(Sponsor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    List<Sponsor> selectByExample(SponsorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    Sponsor selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") Sponsor record, @Param("example") SponsorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByExample(@Param("record") Sponsor record, @Param("example") SponsorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByPrimaryKeySelective(Sponsor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByPrimaryKey(Sponsor record);
}