package com.cppteam.mapper;

import com.cppteam.pojo.UserWx;
import com.cppteam.pojo.UserWxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserWxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int countByExample(UserWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int deleteByExample(UserWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int insert(UserWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int insertSelective(UserWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    List<UserWx> selectByExample(UserWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    UserWx selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserWx record, @Param("example") UserWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByExample(@Param("record") UserWx record, @Param("example") UserWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByPrimaryKeySelective(UserWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbggenerated Thu Oct 26 21:12:04 CST 2017
     */
    int updateByPrimaryKey(UserWx record);
}